# Generated by Django 5.1.7 on 2025-04-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropdiseases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='treatment',
            field=models.TextField(default='No treatment available yet.'),
        ),
    ]
