# Generated by Django 5.1.7 on 2025-04-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropdiseases', '0002_alter_disease_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='crop_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='disease',
            name='disease_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='disease',
            name='treatment',
            field=models.TextField(),
        ),
    ]
